// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uzxjjuursjgymtgfkgxd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV6eGpqdXVyc2pneW10Z2ZrZ3hkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3MzAwMjcsImV4cCI6MjA2NDMwNjAyN30.pEfztfsA_tXjnzvyu43zKYuV0tmpF0HIKzyl5qnVVHU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);